type Block = { type: "p" | "h" | "pull"; text: string };

const bodies: Record<string, Block[]> = {
  "why-we-still-call-it-an-advisor": [
    { type: "p", text: "Language shapes expectation. Call someone an agent, and you expect them to execute. Call someone an advisor, and you expect them to think. The distinction is not cosmetic — it determines whether the first conversation is a transaction or a consultation." },
    { type: "h", text: "The word matters" },
    { type: "p", text: "An agent is measured by speed. An advisor is measured by judgement. When a client calls at midnight because a storm has closed an airport, the agent rebooks the next available seat. The advisor asks: do you actually want to fly tomorrow, or would an extra night in that city be the better trip?" },
    { type: "pull", text: "The distinction is not cosmetic — it determines whether the first conversation is a transaction or a consultation." },
    { type: "p", text: "Travel has more choice than ever and less guidance. The internet gives you every option; an advisor gives you the one that fits. That requires knowing you — how you move, what tires you, what you remember from trips past. None of that lives in a search engine." },
    { type: "h", text: "What this means in practice" },
    { type: "p", text: "It means we turn work down. It means initial calls run long. It means the itinerary arrives as a letter, not a link. It means Isaac reads every brief personally, and if the trip is not right for the practice, he will say so — and usually recommend someone who is." },
    { type: "p", text: "Language is the first design decision. We chose ours carefully." },
  ],
  "the-dolomites-in-late-may": [
    { type: "p", text: "There is a two-week window in the Dolomites when the ski lifts have stopped and the summer hikers have not yet arrived. The refugios are open but quiet. The meadows are half-green, half-snow. The light is colder in the morning and warmer in the afternoon than it will be all year." },
    { type: "h", text: "Why late May" },
    { type: "p", text: "June is the postcard month. But late May has the valleys to yourself. The passes are clear enough to drive but empty enough to stop. The hotels have just reopened, the staff are rested, and the kitchens are cooking with the first spring produce — white asparagus, wild garlic, the earliest strawberries." },
    { type: "pull", text: "The meadows are half-green, half-snow. The light is colder in the morning and warmer in the afternoon than it will be all year." },
    { type: "h", text: "What to expect" },
    { type: "p", text: "Some trails will still be closed above 2,200 metres. That is fine. The valley walks — Pragser Wildsee, the path from Ortisei to Seceda's base — are more than enough. The point is not altitude. The point is silence, and the particular quality of air that only exists in mountains before the season begins." },
    { type: "p", text: "If this window interests you, we plan Dolomites itineraries from mid-April onward. The best rooms book early, because the owners know the secret too." },
  ],
  "cabin-class-isnt-a-personality": [
    { type: "p", text: "Business class is not a personality trait. First class is not an aspiration. These are products — priced, marketed, and sold like any other. The question is never which cabin you can afford. The question is which cabin serves the trip." },
    { type: "h", text: "When business class is wrong" },
    { type: "p", text: "A four-hour flight to a beach holiday does not need a lie-flat seat. The money buys an extra night at the property, a better room, a private transfer that skips the taxi queue. Conversely, a fourteen-hour flight to Tokyo — arriving at 6am with a full day ahead — is a different calculation entirely." },
    { type: "pull", text: "The question is never which cabin you can afford. The question is which cabin serves the trip." },
    { type: "h", text: "What we actually advise" },
    { type: "p", text: "We look at the full arc. Flight length, arrival time, what happens in the first three hours after landing, and how much the ground experience costs relative to the upgrade. Sometimes premium economy on a day flight and the best suite at the hotel is the right trade. Sometimes business overnight and a modest room the first night is better." },
    { type: "p", text: "The point is to build the journey as one piece, not to optimise each segment in isolation. That is what an advisor does differently from a search engine." },
  ],
  "kyoto-without-the-list": [
    { type: "p", text: "Kyoto has a list problem. Fushimi Inari, Arashiyama bamboo, Kinkaku-ji. Every visitor has the same twelve places saved. The city is extraordinary — but not because of the list. It is extraordinary because of the spaces between the famous things." },
    { type: "h", text: "A different pace" },
    { type: "p", text: "One temple a day. A long walk through a residential neighbourhood in between. A sento bath in the afternoon. Dinner at a counter with eight seats. This is the Kyoto that people remember — not the one they photographed." },
    { type: "pull", text: "The city is extraordinary because of the spaces between the famous things." },
    { type: "h", text: "Three practical notes" },
    { type: "p", text: "First: stay in a machiya or a small ryokan, not a hotel. The architecture teaches you the city. Second: book dinner reservations a month early — the good counters seat six, and they are full by Thursday. Third: leave two days with nothing planned. Kyoto reveals itself when you are not looking for it." },
    { type: "p", text: "We shape Kyoto itineraries around a feeling, not a checklist. If you want a week that is quiet, slow, and yours — tell us." },
  ],
  "the-quiet-case-for-river-cruises": [
    { type: "p", text: "River cruising does not photograph well. The ships are smaller. The pools are minimal. The ports are not tropical. And yet it is the most generous format of slow travel we know — because it removes every logistical decision and replaces them with a view that changes while you eat." },
    { type: "h", text: "Why it works" },
    { type: "p", text: "You unpack once. You wake up in a new city. The ship docks centrally — not at a port forty minutes away. You walk off, you walk back. No transfers, no check-ins, no luggage." },
    { type: "pull", text: "It removes every logistical decision and replaces them with a view that changes while you eat." },
    { type: "h", text: "Who it suits" },
    { type: "p", text: "Couples who want to see a region without the driving. Multi-generation families who need a shared base with easy opt-outs. People recovering from a demanding year who want to be carried for a week. It is not for everyone — but for the right traveller, it is difficult to beat." },
    { type: "p", text: "We advise on the Danube, the Rhine, the Douro, the Mekong, and a handful of others. If this format intrigues you, the conversation starts with the region, not the ship." },
  ],
  "what-mexico-isnt": [
    { type: "p", text: "Mexico is not the all-inclusive caricature. It is not the spring-break beach. It is one of the most layered, culturally rich, gastronomically brilliant countries in the Americas — and most travellers see approximately four percent of it." },
    { type: "h", text: "Four corners" },
    { type: "p", text: "Oaxaca for food, mezcal, and textile markets. San Miguel de Allende for architecture and light. The Riviera Nayarit coast — not Cancún — for the Pacific, the surf towns, and the boutique hotels that opened in the last five years. The Yucatán interior for cenotes, ruins, and haciendas that feel nothing like the coast." },
    { type: "pull", text: "Most travellers see approximately four percent of Mexico." },
    { type: "h", text: "What we recommend" },
    { type: "p", text: "Combine two regions. Fly internal. Hire a local driver for the stretches between cities. Eat at markets, not hotel restaurants. And give the trip at least ten days — Mexico rewards people who stay." },
    { type: "p", text: "If you are planning a Mexico trip and do not know where to start, tell us the mood. We will narrow it to two or three places worth your time." },
  ],
  "an-advisors-packing-list": [
    { type: "p", text: "After years on the road, what you carry shrinks. Not because you need less, but because you learn what actually gets used. Here are eleven things that travel with us every time." },
    { type: "h", text: "The list" },
    { type: "p", text: "A hard-sided carry-on with four-wheel spin. One cashmere layer that works on the plane and at dinner. Noise-cancelling headphones — non-negotiable on any flight over four hours. A universal adapter with USB-C. A flat leather pouch for documents. One good pen. A physical notebook. Compression cubes — three, always. A reusable water bottle with a filter. A pocket torch. And a doorstop — the single most underrated hotel-room accessory in existence." },
    { type: "pull", text: "What you carry shrinks. Not because you need less, but because you learn what actually gets used." },
    { type: "h", text: "The philosophy" },
    { type: "p", text: "Pack for the trip, not for possibility. If you have not worn it on the last three trips, it does not come. If you are deciding between two options, take the one that works at both the airport and the restaurant. Versatility beats quantity, always." },
    { type: "p", text: "The best trip is the one where you never think about what you packed." },
  ],
  "the-migration-isnt-a-month": [
    { type: "p", text: "The great migration is marketed as a July event. The crossing. The crocodiles. The drama. In reality, it is a year-round system — two million animals moving in a continuous loop across the Serengeti and Mara ecosystems. There is no off-season. There is only the question of where to be, and when." },
    { type: "h", text: "Reading the system" },
    { type: "p", text: "January to March: calving season in the southern Serengeti. Half a million wildebeest born in six weeks. Predator density at its highest. April to June: the herds move northwest, through the Grumeti corridor. River crossings begin here — smaller, quieter, with fewer vehicles. July to October: the Mara crossing. The one everyone photographs. November to December: the loop closes. Short rains. The herds drift south again." },
    { type: "pull", text: "There is no off-season. There is only the question of where to be, and when." },
    { type: "h", text: "How we plan it" },
    { type: "p", text: "We pick the camp based on the month, not the other way around. Mobile camps that follow the herds. Fixed lodges positioned at known crossing points. And always — always — a buffer day on either side, because wildlife does not keep a calendar." },
    { type: "p", text: "If East Africa is on your mind, the right time to start planning is four to six months ahead. Tell us the window, and we will tell you where to be." },
  ],
  "honeymoons-that-arent-pre-packaged": [
    { type: "p", text: "A honeymoon should feel like the two of you designed it, not like you selected Option C from a brochure. And yet most honeymoon packages are exactly that — a room upgrade, a bottle of champagne, and the same itinerary sold to every couple that week." },
    { type: "h", text: "Six templates we use" },
    { type: "p", text: "The slow coast: two weeks, one region, no more than three properties. The multi-city: four capitals in twelve days, each chosen for something specific. The adventure-romance: safari mornings, beach afternoons, a private island at the end. The off-grid: a single property, no Wi-Fi, no schedule. The cultural: food, markets, cooking classes, temples. The expedition: Antarctica, the Galápagos, or the Norwegian fjords — for couples who prefer wonder to relaxation." },
    { type: "pull", text: "A honeymoon should feel like the two of you designed it." },
    { type: "h", text: "What makes them not feel templated" },
    { type: "p", text: "The small details. A table reserved under a specific tree. A private guide who knows the couple's interests. A surprise day-trip that was not in the itinerary. A handwritten note at turn-down on the last night. These things cost very little and change everything." },
    { type: "p", text: "If you are engaged and beginning to think about the trip, start the conversation early. The best honeymoon properties book six to twelve months ahead." },
  ],
  "the-virtue-of-an-empty-day": [
    { type: "p", text: "Every itinerary we build has at least one day with nothing in it. Not a free day — a truly empty one. No restaurant booked. No museum suggested. No transfer arranged. Just the hotel, the city, and whatever you feel like when you wake up." },
    { type: "h", text: "Why it matters" },
    { type: "p", text: "Planned trips have a momentum problem. Once the schedule starts, it runs. And when it runs for seven or ten or fourteen consecutive days, by day five the traveller is performing the trip rather than experiencing it. The empty day breaks the rhythm. It reminds you that this is a holiday, not a route march." },
    { type: "pull", text: "By day five the traveller is performing the trip rather than experiencing it." },
    { type: "h", text: "What usually happens" },
    { type: "p", text: "People are nervous about it until it arrives. Then they walk somewhere they were not planning to go. They find a café. They sit for two hours. They remember why they came. The empty day almost always produces the story they tell friends when they get home." },
    { type: "p", text: "It is the simplest design decision in travel planning, and the one most itineraries leave out." },
  ],
  "expedition-cruising-honest": [
    { type: "p", text: "Expedition cruising is the fastest-growing segment of the cruise industry. Antarctica, the Galápagos, the high Arctic, the Kimberley coast. The marketing is extraordinary. The price tags are high. And the variance in quality between operators is wider than in any other category." },
    { type: "h", text: "What is worth the cost" },
    { type: "p", text: "The guides. A good expedition ship has naturalists, marine biologists, historians, and photographers who have spent decades in the region. They change the trip completely. The Zodiac landings, the wildlife proximity, and the lecture programme are the product — not the ship itself." },
    { type: "pull", text: "The variance in quality between operators is wider than in any other category." },
    { type: "h", text: "What is not" },
    { type: "p", text: "Spa decks on an ice-class ship. Butler service in a parka. A sommelier at the landing site. These exist because luxury expedition is a marketing category now. They do not make the expedition better. A warm, well-run ship with excellent guides and small landing groups will beat a floating hotel every time." },
    { type: "p", text: "We advise on Ponant, Seabourn Venture, Lindblad, and Hurtigruten for expeditions. The right choice depends on your tolerance for group size, your interest level, and whether you want comfort or immersion. Sometimes both — but it costs more than the brochure suggests." },
  ],
  "shoulder-weeks-we-actually-book": [
    { type: "p", text: "Every destination has a shoulder season — the weeks just before or after the crowds arrive. The weather is almost as good. The prices are noticeably lower. And the experience is disproportionately better, because the places you visit are not performing for volume." },
    { type: "h", text: "Eight stretches" },
    { type: "p", text: "Northern Italy, late May. Japan, early November. The Maldives, late April. Iceland, early September. Greece, mid-October. Kenya, early June. Patagonia, late March. The Amalfi coast, the last week of September. These are not secrets — they are simply less convenient than school holidays and long weekends. That is what makes them better." },
    { type: "pull", text: "The experience is disproportionately better, because the places are not performing for volume." },
    { type: "h", text: "Why we push for them" },
    { type: "p", text: "In a shoulder week, the hotel general manager has time to talk. The restaurant gives you the better table. The hiking trail has twelve people on it, not two hundred. The version of the place you see is the version the locals live in — not the version built for August visitors." },
    { type: "p", text: "If your dates have any flexibility at all, tell us. We will find the shoulder week that fits." },
  ],
  "what-luxury-quietly-means": [
    { type: "p", text: "Luxury in travel used to mean marble, butler service, and a car waiting. It still can. But the word has shifted — and the best properties in the world shifted with it. What luxury means now is harder to photograph and easier to feel." },
    { type: "h", text: "The shift" },
    { type: "p", text: "Time. Privacy. Fewer choices, better made. A room that does not announce its own cost. Service that disappears unless you need it. A kitchen that cooks what arrived that morning, not what the brand mandates across fourteen locations." },
    { type: "pull", text: "What luxury means now is harder to photograph and easier to feel." },
    { type: "h", text: "What we look for" },
    { type: "p", text: "We look for the general manager who walks the grounds at 7am. The property that says no to a wedding request because it would disrupt existing guests. The resort that closes twenty rooms to keep the staff-to-guest ratio. These are the signals. They do not appear in the brochure." },
    { type: "p", text: "If the word luxury means something specific to you — and it always does — tell us what it is. The trip will be better for it." },
  ],
  "the-private-villa-question": [
    { type: "p", text: "The villa-versus-resort question comes up in almost every trip that involves a beach or a countryside property. Both are right in different contexts. The wrong choice is the one made for the wrong reason." },
    { type: "h", text: "When a villa is the answer" },
    { type: "p", text: "Groups. Multi-generation families. Friends travelling together who want a shared base. Couples who want complete privacy without the performance of a resort. Anyone who cooks, or wants to, or who eats at different times from the rest of the world." },
    { type: "pull", text: "The wrong choice is the one made for the wrong reason." },
    { type: "h", text: "When the resort wins" },
    { type: "p", text: "Solo travellers. Couples who want to be cared for without organising anything. Anyone who does not want to think about breakfast. Families with young children who need the safety net of a kids' club. And anyone whose definition of holiday includes other people — the bar, the restaurant, the pool scene." },
    { type: "p", text: "We know villas in Tuscany, Bali, the Greek islands, the South of France, and the Caribbean. We also know when to steer you toward the resort instead. Tell us the trip shape and we will tell you which format serves it." },
  ],
  "family-travel-after-eleven": [
    { type: "p", text: "There is a window in family travel — roughly ages eleven to sixteen — that is harder to plan than any other. The kids' club is no longer interesting. The poolside is boring. The parents want culture. The children want autonomy. And everyone is one bad restaurant away from a mutiny." },
    { type: "h", text: "What works" },
    { type: "p", text: "Active trips. Kayaking, cycling, hiking with a purpose. Cities with street food and markets. Safari — which solves every age simultaneously. Multi-centre trips where each stop has a different flavour. And crucially: one activity per day, not three." },
    { type: "pull", text: "Everyone is one bad restaurant away from a mutiny." },
    { type: "h", text: "What does not" },
    { type: "p", text: "Resort weeks where teenagers have nothing to do. Museum-heavy itineraries without a physical outlet. Back-to-back transfers with no free time. The mistake most families make is overscheduling to keep everyone entertained — when the real solution is giving each person a half-day to do their own thing." },
    { type: "p", text: "Family trips in this age range are one of Isaac's specialisms. If you are planning one and finding it harder than expected — that is normal. Tell us the family, and we will shape the trip around who they actually are." },
  ],
  "on-staying-reachable": [
    { type: "p", text: "Nobody talks about this part of the job. The phone call at 11pm when a volcanic ash cloud grounds flights across Europe. The text at 5am when a hotel has overbooked and the family is standing in a lobby. The email on a Saturday afternoon when a cruise line changes the itinerary with three days' notice." },
    { type: "h", text: "What reachable means" },
    { type: "p", text: "It does not mean 24/7 availability for questions that can wait until Monday. It means that when something goes wrong — genuinely wrong, on the road, with a client mid-trip — there is a human who picks up. Not a call centre. Not a chatbot. A person who knows the trip, knows the client, and can make a decision." },
    { type: "pull", text: "There is a human who picks up. Not a call centre. Not a chatbot." },
    { type: "h", text: "Why it matters" },
    { type: "p", text: "Because the value of an advisor is not visible on a good day. It is visible on the bad one. The rerouted flight. The medical emergency. The missed connection that cascades into three lost bookings. In those moments, having someone who knows what to do — and who is already on it before you finish explaining — is the entire point of the relationship." },
    { type: "p", text: "This is the least glamorous part of the work. It is also the part that makes people come back." },
  ],
  "why-cruise-dining-is-the-quiet-secret": [
    { type: "p", text: "Cruise dining is not about the food, though the food is often extraordinary. It is about the ritual of the table — the same faces each evening, the light changing through the window, wine that tastes different when the ship moves beneath you." },
    { type: "h", text: "The dining room holds the voyage" },
    { type: "p", text: "Main dining happens at a fixed time, at a fixed table, with a fixed team of servers who come to know your preferences before you finish ordering. This is old-fashioned luxury. It is also, curiously, what solo travellers and couples crave on the open water. The formality of it. The ceremony. A reason to dress for dinner when everything else is casual." },
    { type: "pull", text: "Wine tastes different when the ship moves beneath you." },
    { type: "h", text: "Beyond the main dining room" },
    { type: "p", text: "Specialty restaurants on board have their own logic. Some are destination—specific — Italian nights, Japanese tasting menus. Some are theatrical — open kitchens, interactive courses. The best ships vary the venue enough that dinner never feels repetitive, even after fourteen nights at sea." },
    { type: "p", text: "We advise clients to book the specialty venues on the first day. The quiet meals at the main table matter, but a half-dozen dinners elsewhere keeps the experience from flattening. This is how you cruise well." },
  ],
  "the-danube-in-september": [
    { type: "p", text: "The Danube in September is the river at its most generous. The summer tour buses have cleared out. The embassies have closed. The light turns liquid and golden. And the shore — castles, villages, the green hills falling to the water — becomes a narrative that unfolds at five miles per hour." },
    { type: "h", text: "Why late summer matters" },
    { type: "p", text: "June and July are crowded. October begins to feel cool. But September—the vines are beginning to ripen. The restaurants have restored energy after service all summer. The hotel staff have decades under their belt by now and the patience to care." },
    { type: "pull", text: "The light turns liquid and golden." },
    { type: "h", text: "What to expect at the table" },
    { type: "p", text: "River cruises often include drinks and meals. In September these are extraordinary — fresh fish from the river itself, early harvest wines from the valleys above, pastries that smell like the baker's childhood. The food is local and seasonal in the way that ship kitchens rarely achieve." },
    { type: "p", text: "If the Danube calls to you, book for late September. The crowds have departed but the season has not yet ended." },
  ],
  "mediterranean-beyond-the-floating-city": [
    { type: "p", text: "Mediterranean cruising has a Venice problem. Thousands of ships funnel through the lagoon, and Venice is no longer in the Mediterranean — it is a ship port disguised as a city. There is a better way." },
    { type: "h", text: "Where the real coast lives" },
    { type: "p", text: "Hvar. Dubrovnik (on a small ship, early or late season). The Aeolian Islands north of Sicily. Corfu. Ports on the Dalmatian coast that the big ships cannot reach. These are the places where cruise passengers actually see the Mediterranean rather than a postcard of it." },
    { type: "pull", text: "There is a better way to see the sea." },
    { type: "h", text: "The ship size matters" },
    { type: "p", text: "A 6,000-person ship cannot anchor where a 200-person ship can. The enormous vessels must dock at major ports — Venice, Barcelona, Rome. Smaller expedition ships navigate the archipelagos. The experience is not just different — it is a different voyage entirely. More intimate. Less crowded. Actual encounters with shore." },
    { type: "p", text: "We book Mediterranean cruises on smaller lines. The ticket costs more per night, but you are not standing in a queue to board a tender. You are exploring." },
  ],
  "small-ship-cruising-the-case-for-discipline": [
    { type: "p", text: "Small ships — fifty, a hundred souls — move differently than the floating cities. They follow the light. They anchor in bays the big ships cannot enter. They arrive at ports before the tenders start running. And they require a specific kind of traveller: one who wants simplicity over spectacle." },
    { type: "h", text: "The restriction becomes the point" },
    { type: "p", text: "No Broadway shows. No casino. No nightclub. Instead: sunrise on deck. Meals where you recognize the faces around you. An expedition naturalist who knows the coastline. The itinerary changes based on weather and wildlife and captain's intuition. This is not a hotel that floats — it is a ship." },
    { type: "pull", text: "The restriction becomes the point." },
    { type: "h", text: "Who thrives on small ships" },
    { type: "p", text: "Couples who want to be left alone together. Solo travellers who want to meet other thoughtful people. Naturalists and birdwatchers and historians. Anyone allergic to masses and schedules. If the idea of having thirty restaurants on your ship sounds like a feature rather than a bug, a small ship is not for you." },
    { type: "p", text: "We work with expedition operators that have been sailing for decades. The ships are candlelit and modest. The voyages are extraordinary." },
  ],
  "what-we-learned-watching-dawn-at-sea": [
    { type: "p", text: "Seven days at sea teaches you something about time. About who you are when there is nowhere to go and nothing to do but sit on a deck and watch the light change." },
    { type: "h", text: "The first three days are hard" },
    { type: "p", text: "Land-bound, you have forgotten how to sit still. The first morning at sea, people check their phones. The second day, anxiety. By the fourth morning, something shifts. The schedule of sleep and meals becomes enough. The horizon becomes interesting. The sameness — same ocean, same sky — becomes a mirror." },
    { type: "pull", text: "When there is nowhere to go, you stop looking." },
    { type: "h", text: "Days five through seven" },
    { type: "p", text: "Nobody wants to leave. The trip has slowed into something real. Conversations between strangers have become friendships. The morning walk on deck is a ritual. The sunset is anticipated. Time, unmeasured and unhurried, has become the actual commodity — more valuable than the ports, more memorable than the meals." },
    { type: "p", text: "We recommend at least seven days at sea in an itinerary. The first three days are about adaptation. Days four through seven are about transformation." },
  ],
  "alaska-off-season-when-the-glaciers-speak": [
    { type: "p", text: "Alaska in June and July is overrun. Alaska in May — just as the season opens — is still empty. The glaciers are at their most active, calving ice that thunders into the water. The light never quite leaves. And you can hear yourself think." },
    { type: "h", text: "The margins of the season" },
    { type: "p", text: "Most cruise lines begin May sailings, but they do not yet run full capacity. The ships are not fully staffed. The restaurants are less crowded. And the experience of watching a glacier collapse — the slow crack, the roar, the ice tower falling into the sea — becomes something you witness rather than something you perform for Instagram." },
    { type: "pull", text: "The glaciers are at their most active in spring." },
    { type: "h", text: "What to bring" },
    { type: "p", text: "Layered clothing. Rain gear that actually works. Binoculars that do not fog. And patience — the ship will position itself so you can see the glacier face clearly. When it moves, it will move suddenly. Boredom transforms into awe in a single moment." },
    { type: "p", text: "Alaska cruises that depart in May feel like a secret. Because they still are." },
  ],
  "balcony-versus-suite-the-real-answer": [
    { type: "p", text: "The cabin question comes up in every cruise consultation. Balcony or suite? Inside or outside? The marketing answer is clear. The truth is more nuanced." },
    { type: "h", text: "What the brochure does not tell you" },
    { type: "p", text: "A balcony on a big ship faces other cabins. The view is narrower than you think. An inside cabin with a window that shows the corridor is, in practice, indistinguishable from an inside cabin with no window. But a suite with a real balcony — teak railing, lounge chairs, privacy — is a different experience entirely." },
    { type: "pull", text: "A balcony on a big ship faces other cabins." },
    { type: "h", text: "How we advise it" },
    { type: "p", text: "For seven days or less, an inside cabin and money saved for specialty dining. For fourteen days or longer, an actual suite or a mid-deck balcony on a small ship where privacy exists. The calculus changes based on trip length and ship size. Neither is objectively better — only better for the specific voyage you are taking." },
    { type: "p", text: "Tell us the cruise, and we will tell you which cabin serves it." },
  ],
  "the-galápagos-at-depth": [
    { type: "p", text: "The Galápagos exists in another time. Evolution paused there. The animals do not fear. The landscape is raw — no soil, all volcanic. A naturalist standing on deck becomes your translator into the oldest operating laboratory on Earth." },
    { type: "h", text: "Why expedition matters" },
    { type: "p", text: "The Galápagos through expedition cruising is a PhD seminar on wheels. The naturalists are often scientists who have spent years studying the islands. They can point to a finch and tell you its species, its diet, its adaptation to an El Niño year. Every landing becomes dense with meaning." },
    { type: "pull", text: "The naturalists can point to a finch and tell you its whole story." },
    { type: "h", text: "The rhythm of the days" },
    { type: "p", text: "Early morning wake-up. Zodiac landing. Walk with a naturalist through volcanic rock and giant tortoises and unique seabirds that have never learned to fear humans. Lunch on the ship. Afternoon lecture in air conditioning. Sunset on deck. Dinner that tastes better because of what you saw that morning." },
    { type: "p", text: "The Galápagos is not a relaxation cruise. It is a voyage of discovery. Book it as such." },
  ],
  "caribbean-beyond-the-resort-pier": [
    { type: "p", text: "Caribbean cruising has a formula problem. Cruise port, beach day, cocktail, repeat. But the Caribbean is not a formula — it is a collection of incredibly distinct islands, each with its own food, rhythm, and story." },
    { type: "h", text: "Where the real islands live" },
    { type: "p", text: "Barbuda — not Antigua. The Grenadines rather than the Grenadines cruise port. Bequía for the market and the catch of the day. Dominica for the rainforest hike and the genuine hospitality of people who rarely see tourists. Bequia for dive shops run by locals, not cruise companies." },
    { type: "pull", text: "The Caribbean is not a formula — it is a collection of stories." },
    { type: "h", text: "How small ships navigate it" },
    { type: "p", text: "Expedition and smaller cruise lines anchor at islands that the big ships cannot reach. That simple fact changes everything. You arrive at a dock, not a cruise terminal. The locals have not been trained to sell you something. The restaurants serve what they caught that morning." },
    { type: "p", text: "Caribbean cruises on small ships cost more per night. You get actual Caribbean, not the airport-resort version." },
  ],
  "transatlantic-crossing-the-luxury-of-slowness": [
    { type: "p", text: "A seven-day transatlantic crossing is perhaps the closest thing modern travel offers to old-world ocean voyaging. You leave New York or Europe. You sail across the Atlantic. You arrive elsewhere. No ports. No tenders. No rushing." },
    { type: "h", text: "What empty days at sea offer" },
    { type: "p", text: "The ship becomes a village. You know the faces. Dinners are anticipated. The library — actual books, quiet corners — becomes important. Conversations with strangers last three hours. The rhythm of sea-time — the swell, the light, the appetite that comes from salt air — becomes your metronome." },
    { type: "pull", text: "The ship becomes a village." },
    { type: "h", text: "Why it matters" },
    { type: "p", text: "Transatlantic crossings connect two worlds with nothing between but time. You are suspended. Modern life cannot reach you. And when you arrive — disoriented, calm, changed — you understand why people used to cross by ship. Not because of the destination. Because of the crossing itself." },
    { type: "p", text: "We book transatlantic voyages in both directions, in both seasons. If this appeals to you, the planning begins six months ahead." },
  ],
  "peruvian-amazon-by-riverboat": [
    { type: "p", text: "The Amazon by riverboat is not a cruise — it is an immersion. The jungle is alive with sound. The water is high and muddy and alive with anacondas and pink dolphins. The lodge is a collection of cabins connected by boardwalks, and you are inside something older than you can fully comprehend." },
    { type: "h", text: "The rhythm of expedition" },
    { type: "p", text: "Pre-dawn wake-up. Paddle canoe into the flooded forest. Return for breakfast. Sleep. Late-afternoon hike inland. Nighttime caiman spotting from a small boat. Dinner — jungle cuisine that tastes like the rainforest." },
    { type: "pull", text: "The jungle is older than you can fully comprehend." },
    { type: "h", text: "What you learn" },
    { type: "p", text: "The naturalist becomes indispensable. Every sound, every movement, every flash of color — they have a name and a story. The isolation becomes clarifying. The constant hum of life outside your cabin becomes a meditation. This is not leisurely. It is intense and transformative." },
    { type: "p", text: "Amazon expeditions by boat suit people who want immersion, not comfort. We work with experienced lodges that prioritize safety and naturalist quality above all." },
  ],
  "asia-pacific-cruising-the-quiet-compass": [
    { type: "p", text: "Asia-Pacific cruising is the frontier of small-ship expeditions. The routes are not well-worn. The ships are nimble. The ports are often genuine rather than tourist-trained." },
    { type: "h", text: "Where small ships excel" },
    { type: "p", text: "Southeast Asia island-hopping. The Mekong River. New Zealand fjords. The coast of Tasmania. These regions are too remote or geographically complicated for big ships, so they remain navigated by expedition vessels with local knowledge." },
    { type: "pull", text: "The ports are genuine rather than tourist-trained." },
    { type: "h", text: "The advantage of the compass" },
    { type: "p", text: "The ship's captain, sitting with naturalists and locals, decides the next destination based on weather, wildlife sightings, and village festivals. The itinerary is not fixed — it is suggested. This level of flexibility creates experiences that cannot be guaranteed or booked in advance." },
    { type: "p", text: "Asia-Pacific voyages suit explorers who want some uncertainty. And who trust the expertise of the people aboard." },
  ],
  "ports-we-tell-nobody-about": [
    { type: "p", text: "The best Mediterranean ports are not on the cruise ship schedules. They are too small. Too steep. Too unknown. And therefore too perfect." },
    { type: "h", text: "Where the secret is kept" },
    { type: "p", text: "A fishing village on the Dalmatian coast where the restaurant serves grilled fish you watched them pull from the boat that morning. A Greek island with a single hotel and a single taverna and light so clear it hurts. A Portuguese riverside town where the wine comes from the vineyard visible from your table." },
    { type: "pull", text: "The best ports are too small, too steep, too unknown." },
    { type: "h", text: "How to find them" },
    { type: "p", text: "Book a small ship. Talk to the captain. Ask the crew where they go when they are not working. Read old travel journals. And accept that sometimes the destination is not on the plan — it is a suggestion that becomes reality because someone aboard knows where to look." },
    { type: "p", text: "The best ports are still secrets because they remain uncrowded. Let's keep it that way." },
  ],
  "night-sailing-the-romance-is-real": [
    { type: "p", text: "The moment the sun sets on your first night sailing — the moment land disappears and the ship is alone in an ocean that is alone — something breaks open. The air smells different. The stars are different. You are truly at sea." },
    { type: "h", text: "Why nighttime on water matters" },
    { type: "p", text: "City-bound, we live in light pollution. We forget what night actually looks like. At sea, you remember. The stars are overwhelming. The moon casts a path across the water. The ship's engines are the only sound. And you are standing at the rail understanding why people once crossed oceans in wooden boats on faith." },
    { type: "pull", text: "You are truly at sea." },
    { type: "h", text: "Who it calls to" },
    { type: "p", text: "Couples seeking romance in the truest sense. Solo travellers who want to remember what solitude feels like. Anyone recovering from a year of noise. Night sailing on an open deck becomes the kind of memory that shapes how you see the world afterward." },
    { type: "p", text: "We recommend staying awake your first night sailing. The sunrise is good, but the night is unforgettable." },
  ],
  "the-captain-knows": [
    { type: "p", text: "The captain of a ship is not a figurehead. The captain is the decision-maker, the educator, the person who knows where the ship goes when conditions change. And the best captains can tell you why." },
    { type: "h", text: "Experience is visible" },
    { type: "p", text: "A captain who has sailed a route for twenty years will position the ship so you see the glacier differently than a captain on their first voyage. They know the angle of light, the movement of whales, the timing of tides. Their knowledge is felt, not spoken." },
    { type: "pull", text: "A captain who has sailed a route for twenty years knows the angle of light." },
    { type: "h", text: "Why it matters to your cruise" },
    { type: "p", text: "The captain's expertise becomes the expedition's backbone. When the weather changes, they know which anchorage is best. When wildlife appears, they know how long it will stay. When a guest becomes ill, they have protocols and experience. This is why small expedition ships, with the same captain year after year, create better voyages than floating cities with rotating crews." },
    { type: "p", text: "Ask your cruise line about the captain's experience. It matters more than you think." },
  ],
  "norwegian-fjords-in-the-midnight-sun": [
    { type: "p", text: "Norwegian fjords in summer are the closest thing to enchantment available on a cruise. Waterfalls fall from vertical cliffs into water so blue it seems impossible. Glaciers calve ice towers. And the light — the light never quite leaves." },
    { type: "h", text: "Why the midnight sun changes everything" },
    { type: "p", text: "You can read a book on deck at 2am. You can hike a mountain at 11pm. The day extends impossibly. And as the light stretches, so does your sense of wonder — the waterfalls are more beautiful in low-angle light, the mountains are sharper, the experience becomes dreamlike." },
    { type: "pull", text: "The light never quite leaves." },
    { type: "h", text: "What to plan for" },
    { type: "p", text: "Book a small ship — the fjords are too narrow and dramatic for large vessels. Plan excursions that happen in late evening when the light turns golden. Bring sleeping medication if you need darkness to rest. And accept that you will be moving slowly, intentionally, through landscapes that do not feel like the rest of the world." },
    { type: "p", text: "Norwegian fjords in summer cost more than winter cruises. They are worth every penny." },
  ],
  "canal-cruising-art-and-engineering": [
    { type: "p", text: "The Panama Canal. The Corinth Canal. The Kiel Canal. These are not just waterways — they are engineering marvels that changed how the world moves. Transiting them on a ship is to feel history in your bones." },
    { type: "h", text: "The engineering becomes the narrative" },
    { type: "p", text: "Watching your ship rise and fall through locks — the walls inches from the deck, the machinery working invisibly — you understand human ambition. The canal was built by people who wanted to connect continents that were meant to be separate. And it worked." },
    { type: "pull", text: "The walls inches from the deck." },
    { type: "h", text: "Which canal to choose" },
    { type: "p", text: "The Panama Canal is dramatic — you pass from Atlantic to Pacific in an afternoon. The Corinth Canal is intimate — your ship fills the entire waterway. The Kiel Canal connects the North Sea to the Baltic in a single day of incredible geology. All are worth sailing. All change how you understand geography." },
    { type: "p", text: "Canal transits are often part of longer itineraries, not the whole voyage. But they deserve top billing in your planning." },
  ],
  "adventure-cruising-with-purpose": [
    { type: "p", text: "Adventure cruising is the frontier of expedition travel. Ice-class ships breaking through Arctic ice. Kayaks launched from the bow into wildlife-rich passages. Naturalists who are PhD-level scientists. Voyages to places that most people will never see." },
    { type: "h", text: "What separates it from tourism" },
    { type: "p", text: "Purpose. Every landing has a reason — a wildlife observation, a geological formation, a community interaction. You are not there to tick a box. You are there to understand something about the world." },
    { type: "pull", text: "You are not there to tick a box." },
    { type: "h", text: "The voyages that matter" },
    { type: "p", text: "Antarctica, where you see penguins and seals in their habitat. The Galápagos, where evolution is visible. The Northwest Passage, where Arctic exploration becomes real. These voyages are expensive and demanding. They are also transformative — the kind of trips you reference for the rest of your life." },
    { type: "p", text: "We book adventure cruises for people who want to see the world before it changes. The time to go is now." },
  ],
  "the-dining-room-at-eight": [
    { type: "p", text: "Formal dining on a cruise ship is a ritual that modern travel has nearly abandoned. And it is exactly what makes it necessary." },
    { type: "h", text: "The formality is the point" },
    { type: "p", text: "You dress for dinner. You arrive at a fixed time. You sit at a table with the same people each evening. The silverware is real. The wine is selected by people who know wine. The courses arrive with ceremony. For people used to eating from screens, this feels revolutionary." },
    { type: "pull", text: "For people used to eating from screens, this feels revolutionary." },
    { type: "h", text: "Who still does formal dining" },
    { type: "p", text: "The better expedition cruise lines. River cruise operators. Smaller, more traditional vessels. If your cruise line's marketing emphasizes casual dining and multiple venues, you are on a ship designed for volume. If it mentions formal nights and assigned seating, you are on a ship designed for experience." },
    { type: "p", text: "We seek out cruises with formal dining options. The ritual matters." },
  ],
  "champagne-and-sunsets-the-ritual": [
    { type: "p", text: "Every evening on a cruise, the sun sets. And if you are wise, you will stop what you are doing to watch it. Better still if you do it with champagne in hand, or a cocktail, or simply a glass of water that tastes clearer when the light turns orange." },
    { type: "h", text: "The ritual is meditation" },
    { type: "p", text: "Sunset at sea is different than sunset on land. The light lives longer. The colors are more saturated. And because you are moving, the sunset moves with you — the whole horizon becomes a canvas." },
    { type: "pull", text: "The ritual is meditation." },
    { type: "h", text: "How to do it right" },
    { type: "p", text: "Find a quiet spot on deck. Arrive five minutes before you think the sun will set. Stay for five minutes after. Notice how the light changes the ship, the water, the other passengers. Notice how it changes you." },
    { type: "p", text: "The best part of cruise travel is not the ports. It is the hours between them. This is when you remember why you came." },
  ],
  "deck-chairs-and-philosophy": [
    { type: "p", text: "A week in a deck chair at sea teaches you something about idleness. About doing nothing with intention. About how the mind works when there is no screen, no agenda, no place to be but here." },
    { type: "h", text: "What happens when you stop" },
    { type: "p", text: "The first two days, your mind churns. You run through work problems, life problems, projects started. By day three, the churn slows. By day five, you have forgotten what you were churning about. By day seven, you have become a different person — calmer, more present, less certain about what matters." },
    { type: "pull", text: "By day five, you have forgotten what you were churning about." },
    { type: "h", text: "Why this is valuable" },
    { type: "p", text: "In normal life, you never know if clarity is real or just exhaustion. At sea, clarity persists. The pace is slow enough that you can trust it. This is why people return from cruises changed. Not because of the places. Because of the time they spent sitting and becoming themselves again." },
    { type: "p", text: "We recommend a minimum of seven days. The transformation takes time." },
  ],
  "crew-conversations-the-human-element": [
    { type: "p", text: "The crew of a ship is invisible until it is not. And when you actually talk to a server, a housekeeper, a deck officer, you realize they carry stories that shape the voyage more than the itinerary does." },
    { type: "h", text: "The work behind the experience" },
    { type: "p", text: "A housekeeper in the cabin every day becomes a person — ask their name, learn where they are from, ask about their family. They have worked on this ship for three, five, ten years. They have seen hundreds of passengers. They know which tables have the best views, which staff members are excellent, which ports are worth exploring." },
    { type: "pull", text: "The crew is invisible until it is not." },
    { type: "h", text: "Why conversations matter" },
    { type: "p", text: "The voyage is built by people, not computers. Talking to crew humanizes the experience. You stop seeing the ship as a service provider and start seeing it as a community — one you are briefly part of." },
    { type: "p", text: "We advise all clients to ask crew members for recommendations. Their suggestions are always better than the guidebook." },
  ],
  "library-at-sea-when-books-float": [
    { type: "p", text: "The ship's library is a strange and wonderful place. A room full of books that have been read by hundreds of passengers, now sitting on shelves in the middle of the ocean, waiting for you to pick them up." },
    { type: "h", text: "Why it matters" },
    { type: "p", text: "In our screens-first life, finding a room full of books feels like discovering an artifact. Better still, you have nowhere to be. No appointment after this chapter. No email waiting. You can read until you fall asleep in a deck chair, and nobody will mind." },
    { type: "pull", text: "No appointment after this chapter." },
    { type: "h", text: "The books people finish at sea" },
    { type: "p", text: "The long novels that seemed impossible on land become readable. The poetry collections that felt inaccessible suddenly make sense. The guidebooks sit untouched — because you are not trying to see everything anymore. You are trying to see a few things slowly." },
    { type: "p", text: "Bring a book you started and abandoned. You might finish it at sea." },
  ],
  "itinerary-discipline-the-unbooked-day": [
    { type: "p", text: "The worst thing you can do on a cruise is book every excursion. The best thing you can do is plan to do nothing — and mean it." },
    { type: "h", text: "Why staying aboard is radical" },
    { type: "p", text: "Everyone else is racing to the port. You sleep in. You order room service. You sit in a mostly empty dining room. You read. You nap. By afternoon, you have barely left the ship — and yet you feel more rested than you have in years." },
    { type: "pull", text: "The best days are the ones you plan to do nothing." },
    { type: "h", text: "Permission to pause" },
    { type: "p", text: "FOMO is real at sea — everyone else is snorkeling, hiking, exploring. But you can explore tomorrow. Today you can sit on deck and read and remember what it feels like to do one thing at a time." },
    { type: "p", text: "We advise: book 40% of the days with excursions. Leave 60% unscheduled. The balance is where the voyage becomes real." },
  ],
  "secret-spots-hidden-on-big-ships": [
    { type: "p", text: "Even on a cruise ship with 6,000 passengers, solitude exists. You just have to know where to look." },
    { type: "h", text: "Where passengers rarely venture" },
    { type: "p", text: "The forward observation deck at dawn. The library at 3pm. A quiet corner of the pool deck during formal dinner. The crew's exercise room, if you ask nicely. The very top of the ship, where the wind is loud and the view is unobstructed." },
    { type: "pull", text: "Even on big ships, solitude exists." },
    { type: "h", text: "How to find your spot" },
    { type: "p", text: "Explore during times when most passengers are eating or sleeping. Look for spaces that are not advertised. Talk to crew — they know the quiet corners. Arrive early. Stay late. The ship reveals itself to people who move slowly." },
    { type: "p", text: "Your favorite spot on the ship will change how you experience the voyage." },
  ],
  "spring-cruising-the-season-nobody-books": [
    { type: "p", text: "March and April — spring cruising — is when astute travellers book. The weather is fine but unpredictable. The prices have not yet peaked. And the ships are not yet full of families." },
    { type: "h", text: "Why spring is underrated" },
    { type: "p", text: "School is still in session. Families are still home-bound. Adults book but feel scattered. The restaurants are never full. The deck chairs are plentiful. The crew still has energy — they have not been running eight months of back-to-back sailings." },
    { type: "pull", text: "The crew still has energy." },
    { type: "h", text: "Where to go in spring" },
    { type: "p", text: "The Mediterranean before the summer crush. The Caribbean in the calmer shoulder season. Northern Europe as the ice melts and the days lengthen. Alaska's opening weeks before the tourist ships arrive in mass." },
    { type: "p", text: "Spring cruising is a secret that is easy to keep because it is counterintuitive. Book it." },
  ],
  "the-first-morning-at-sea": [
    { type: "p", text: "There is a moment on the first morning of a cruise — after the engines have stopped building, after land has become invisible — when you realize you are in a different world." },
    { type: "h", text: "The shift is physical" },
    { type: "p", text: "The deck moves differently. The air tastes like salt and freedom. The sounds are ocean sounds — no traffic, no sirens, no hum of cities. You are on a ship in the middle of water. There is nowhere else to go. And something in your chest loosens." },
    { type: "pull", text: "When land becomes invisible, you become possible." },
    { type: "h", text: "What to do with this moment" },
    { type: "p", text: "Get on deck before breakfast. Watch the ocean. Let the magnitude of it sink in. The voyage has officially begun — not when you boarded, but now, when land disappears and you are part of something older than cities." },
    { type: "p", text: "The first morning at sea is why people cruise. Everything after that is bonus." },
  ],
  "wine-and-water-tasting-the-voyage": [
    { type: "p", text: "A sommelier aboard a cruise ship knows something about water that landlocked people do not — it tastes different when the ship moves through it." },
    { type: "h", text: "The science of tasting at sea" },
    { type: "p", text: "The swell, the speed, the humidity, the salt air — all of these things change how your palate works. Wine tastes rounder at sea. Water tastes fresher. And because there are few distractions, you actually notice." },
    { type: "pull", text: "Wine tastes rounder at sea." },
    { type: "h", text: "The sommelier's recommendations" },
    { type: "p", text: "Book wine tastings on the first evening. Talk to the wine staff — they know which wines travel well and which arrive changed. And try local wines at each port. The wine from the island, drunk at the island, becomes part of the voyage in a way that duty-free wine cannot." },
    { type: "p", text: "Wine and water — the simplest pleasures are often the most memorable." },
  ],
  "star-gazing-from-a-moving-ship": [
    { type: "p", text: "Away from land, away from light pollution, the stars are overwhelming. And watching them from a moving ship — the deck beneath you shifting gently — connects you to centuries of seafarers who navigated by these exact lights." },
    { type: "h", text: "What the dark brings" },
    { type: "p", text: "The Milky Way becomes a river across the sky. Satellites cross predictably. Shooting stars appear constantly. And the vastness — the simple fact that you are seeing the universe from a ship in the middle of an ocean — becomes transcendent." },
    { type: "pull", text: "The stars are overwhelming away from land." },
    { type: "h", text: "When and where" },
    { type: "p", text: "The Southern Hemisphere has clearer skies. Winter sailings have longer nights. And a ship positioned away from city lights shows the stars better than even a remote island does — because the constant motion of the deck beneath you makes you hyperaware." },
    { type: "p", text: "Bring a blanket and stay on deck after midnight. Astronomers sail for this exact reason." },
  ],
  "crossing-the-date-line-time-travel": [
    { type: "p", text: "Crossing the international date line on a cruise is the closest thing travel offers to time travel. You leave Tuesday, you arrive on Tuesday. The calendar breaks. And something opens in you." },
    { type: "h", text: "The philosophy of a lost day" },
    { type: "p", text: "The ship simply skips a day. Everyone agrees to pretend it never happened. It is the same day twice, or not at all, depending on how you think about it. And the brain, briefly, forgets how to understand linear time." },
    { type: "pull", text: "The calendar breaks." },
    { type: "h", text: "Why it changes perspective" },
    { type: "p", text: "For a moment, you stop believing in the certainty of time. You understand that time is arbitrary, constructed, negotiable. And somehow that small break in consensus reality shifts how you see everything else." },
    { type: "p", text: "Crossing the date line is a small magic trick that works every time." },
  ],
};

const defaultBody: Block[] = [
  { type: "p", text: "There is a version of this category that everyone seems to write. It opens with a sweeping claim, lists ten things, and tells you that the writer has Just Been. This is not one of those." },
  { type: "h", text: "A small framing" },
  { type: "p", text: "Before any of the specifics, three things are worth saying out loud. The first is that taste is a discipline, not a feeling. The second is that the right trip is almost never the most expensive one. And the third — perhaps the most important — is that the difference between a good trip and a remembered one is almost always made in the quiet hours of planning, not on the road itself." },
  { type: "pull", text: "The difference between a good trip and a remembered one is almost always made in the quiet hours of planning." },
  { type: "h", text: "What we look for" },
  { type: "p", text: "In the property, we look for service that disappears. We look for design that does not announce itself. We look for a general manager who knows the staff by name, and a kitchen that buys local and writes its own menu." },
  { type: "p", text: "In the itinerary, we look for breathing room. The empty afternoon, the unscheduled walk, the dinner reservation you do not have to keep. The rhythm of a trip is built in the gaps." },
  { type: "h", text: "A note in closing" },
  { type: "p", text: "If any of this resonates, the next step is simple. Tell us the shape of the trip. We will read it carefully. And then, in a day or two, we will come back to you with one quietly considered plan." },
];

export function getBlogBody(slug: string): Block[] {
  return bodies[slug] ?? defaultBody;
}
