export interface Post {
  slug: string;
  title: string;
  dek: string;          // short editorial subhead
  category: string;
  read: string;         // "8 min read"
  date: string;         // "April 2026"
  image: string;
  author: string;
  feature?: boolean;
}

/**
 * Hand-curated editorial roll. 16 entries, used by /blog and /blog/[slug].
 */
export const posts: Post[] = [
  {
    slug: "why-we-still-call-it-an-advisor",
    title: "Why we still call it an advisor, not an agent",
    dek: "A short note on language, and why the word you choose for the job shapes the work itself.",
    category: "Field notes",
    read: "6 min read",
    date: "May 2026",
    image: "/images/blog/why-we-still-call-it-an-advisor.jpg",
    author: "Isaac",
    feature: true,
  },
  {
    slug: "the-dolomites-in-late-may",
    title: "The Dolomites in late May",
    dek: "When the lifts have stopped and the wildflowers haven't quite started — the quietest two weeks of the alpine year.",
    category: "Destinations",
    read: "8 min read",
    date: "April 2026",
    image: "/images/blog/the-dolomites-in-late-may.jpg",
    author: "Isaac",
  },
  {
    slug: "cabin-class-isnt-a-personality",
    title: "Cabin class isn't a personality",
    dek: "Choosing a long-haul flight by who you are, not by what's on the upgrade menu.",
    category: "Flights",
    read: "5 min read",
    date: "April 2026",
    image: "/images/blog/cabin-class-isnt-a-personality.jpg",
    author: "Isaac",
  },
  {
    slug: "kyoto-without-the-list",
    title: "Kyoto, without the list",
    dek: "A week in Kyoto for people who don't want to tick anything. Walks, baths, three quiet meals.",
    category: "Destinations",
    read: "9 min read",
    date: "March 2026",
    image: "/images/blog/kyoto-without-the-list.jpg",
    author: "Isaac",
  },
  {
    slug: "the-quiet-case-for-river-cruises",
    title: "The quiet case for river cruises",
    dek: "Once you're past the marketing, river cruising is the most generous slow-travel format we know.",
    category: "Cruises",
    read: "7 min read",
    date: "March 2026",
    image: "/images/blog/the-quiet-case-for-river-cruises.jpg",
    author: "Isaac",
  },
  {
    slug: "what-mexico-isnt",
    title: "What Mexico isn't",
    dek: "A long-form correction to the all-inclusive caricature, and four corners of the country to actually visit.",
    category: "Destinations",
    read: "11 min read",
    date: "February 2026",
    image: "/images/blog/what-mexico-isnt.jpg",
    author: "Isaac",
  },
  {
    slug: "an-advisors-packing-list",
    title: "An advisor's packing list",
    dek: "The eleven things we travel with, after twenty years on the road.",
    category: "Field notes",
    read: "6 min read",
    date: "February 2026",
    image: "/images/blog/an-advisors-packing-list.jpg",
    author: "Isaac",
  },
  {
    slug: "the-migration-isnt-a-month",
    title: "The migration isn't a month",
    dek: "Why the great migration is a year-round system, and how to read it before you book.",
    category: "Safari",
    read: "10 min read",
    date: "January 2026",
    image: "/images/blog/the-migration-isnt-a-month.jpg",
    author: "Isaac",
  },
  {
    slug: "honeymoons-that-arent-pre-packaged",
    title: "Honeymoons that aren't pre-packaged",
    dek: "Six honeymoon templates we genuinely use, and the small details that make them not feel templated.",
    category: "Romance",
    read: "8 min read",
    date: "January 2026",
    image: "/images/blog/honeymoons-that-arent-pre-packaged.jpg",
    author: "Isaac",
  },
  {
    slug: "the-virtue-of-an-empty-day",
    title: "The virtue of an empty day",
    dek: "Why we leave one un-planned day per week in every itinerary, on purpose.",
    category: "Field notes",
    read: "4 min read",
    date: "December 2025",
    image: "/images/blog/the-virtue-of-an-empty-day.jpg",
    author: "Isaac",
  },
  {
    slug: "expedition-cruising-honest",
    title: "Expedition cruising, honestly",
    dek: "Antarctica, the Galápagos, the high Arctic. What's worth the cost, and what isn't.",
    category: "Cruises",
    read: "9 min read",
    date: "December 2025",
    image: "/images/blog/expedition-cruising-honest.jpg",
    author: "Isaac",
  },
  {
    slug: "shoulder-weeks-we-actually-book",
    title: "Shoulder weeks we actually book",
    dek: "Eight stretches of the year that are quietly better than the postcard months.",
    category: "Field notes",
    read: "7 min read",
    date: "November 2025",
    image: "/images/blog/shoulder-weeks-we-actually-book.jpg",
    author: "Isaac",
  },
  {
    slug: "what-luxury-quietly-means",
    title: "What luxury quietly means, in 2026",
    dek: "Less marble, more time. A short essay on the shift inside the category.",
    category: "Essays",
    read: "6 min read",
    date: "November 2025",
    image: "/images/blog/what-luxury-quietly-means.jpg",
    author: "Isaac",
  },
  {
    slug: "the-private-villa-question",
    title: "The private villa question",
    dek: "When a villa is the right answer, and when the resort suite is the better one.",
    category: "Hotels",
    read: "8 min read",
    date: "October 2025",
    image: "/images/blog/the-private-villa-question.jpg",
    author: "Isaac",
  },
  {
    slug: "family-travel-after-eleven",
    title: "Family travel, after eleven",
    dek: "The trips that work once the kids stop wanting the kids' club, and before they stop wanting to come at all.",
    category: "Family",
    read: "7 min read",
    date: "October 2025",
    image: "/images/blog/family-travel-after-eleven.jpg",
    author: "Isaac",
  },
  {
    slug: "on-staying-reachable",
    title: "On staying reachable",
    dek: "A short note on the part of the job nobody talks about — being on the phone when it matters.",
    category: "Field notes",
    read: "5 min read",
    date: "September 2025",
    image: "/images/blog/on-staying-reachable.jpg",
    author: "Isaac",
  },
  {
    slug: "why-cruise-dining-is-the-quiet-secret",
    title: "Why cruise dining is the quiet secret",
    dek: "Between the specialty venues and unscheduled moments, the tables hold the whole trip. An essay on eating on the water.",
    category: "Cruises",
    read: "10 min read",
    date: "June 2026",
    image: "/images/blog/why-cruise-dining-is-the-quiet-secret.jpg",
    author: "Isaac",
  },
  {
    slug: "the-danube-in-september",
    title: "The Danube in September",
    dek: "When the summer crowds have scattered and the light turns golden—the river reveals itself to the patient traveler.",
    category: "Cruises",
    read: "8 min read",
    date: "June 2026",
    image: "/images/blog/the-danube-in-september.jpg",
    author: "Isaac",
  },
  {
    slug: "mediterranean-beyond-the-floating-city",
    title: "Mediterranean beyond the floating city",
    dek: "Skip the ports-of-call script. Where to truly anchor in Greece, Croatia, and the quieter corners of Italy.",
    category: "Cruises",
    read: "11 min read",
    date: "May 2026",
    image: "/images/blog/mediterranean-beyond-the-floating-city.jpg",
    author: "Isaac",
  },
  {
    slug: "small-ship-cruising-the-case-for-discipline",
    title: "Small-ship cruising: the case for discipline",
    dek: "Why the restriction—shallow draft, candlelit cabins, fifty souls—becomes the whole point of the voyage.",
    category: "Cruises",
    read: "7 min read",
    date: "May 2026",
    image: "/images/blog/small-ship-cruising-the-case-for-discipline.jpg",
    author: "Isaac",
  },
  {
    slug: "what-we-learned-watching-dawn-at-sea",
    title: "What we learned watching dawn at sea",
    dek: "Three weeks observing how travelers change when time stops. A meditation on days without itineraries.",
    category: "Cruises",
    read: "6 min read",
    date: "May 2026",
    image: "/images/blog/what-we-learned-watching-dawn-at-sea.jpg",
    author: "Isaac",
  },
  {
    slug: "alaska-off-season-when-the-glaciers-speak",
    title: "Alaska off-season: when the glaciers speak",
    dek: "Late spring before the ships arrive. Longer days, fewer tourists, and the ice beginning its ancient music.",
    category: "Cruises",
    read: "9 min read",
    date: "April 2026",
    image: "/images/blog/alaska-off-season-when-the-glaciers-speak.jpg",
    author: "Isaac",
  },
  {
    slug: "balcony-versus-suite-the-real-answer",
    title: "Balcony versus suite: the real answer",
    dek: "Neither the marketing nor the specifications tell the truth. What a decade of cruise planning has taught us about staterooms.",
    category: "Cruises",
    read: "8 min read",
    date: "April 2026",
    image: "/images/blog/balcony-versus-suite-the-real-answer.jpg",
    author: "Isaac",
  },
  {
    slug: "the-galápagos-at-depth",
    title: "The Galápagos at depth",
    dek: "Expedition cruising where naturalists are poets, and every landing matters. What makes the archipelago unforgettable.",
    category: "Cruises",
    read: "10 min read",
    date: "March 2026",
    image: "/images/blog/the-galápagos-at-depth.jpg",
    author: "Isaac",
  },
  {
    slug: "caribbean-beyond-the-resort-pier",
    title: "Caribbean beyond the resort pier",
    dek: "Islands aren't one thing. How to know when to anchor at Barbuda, when to sail deeper into the Grenadines.",
    category: "Cruises",
    read: "9 min read",
    date: "March 2026",
    image: "/images/blog/caribbean-beyond-the-resort-pier.jpg",
    author: "Isaac",
  },
  {
    slug: "transatlantic-crossing-the-luxury-of-slowness",
    title: "Transatlantic crossing: the luxury of slowness",
    dek: "Seven days between continents. Why this voyage rewrites what travelers think they want from a cruise.",
    category: "Cruises",
    read: "11 min read",
    date: "February 2026",
    image: "/images/blog/transatlantic-crossing-the-luxury-of-slowness.jpg",
    author: "Isaac",
  },
  {
    slug: "peruvian-amazon-by-riverboat",
    title: "Peruvian Amazon by riverboat",
    dek: "Where the jungle teaches patience, and the naturalist becomes your translator into green noise.",
    category: "Cruises",
    read: "9 min read",
    date: "January 2026",
    image: "/images/blog/peruvian-amazon-by-riverboat.jpg",
    author: "Isaac",
  },
  {
    slug: "asia-pacific-cruising-the-quiet-compass",
    title: "Asia-Pacific cruising: the quiet compass",
    dek: "From Southeast Asia to the Indian Ocean, smaller ships navigate where others fear. A different kind of luxury.",
    category: "Cruises",
    read: "10 min read",
    date: "January 2026",
    image: "/images/blog/asia-pacific-cruising-the-quiet-compass.jpg",
    author: "Isaac",
  },
  {
    slug: "ports-we-tell-nobody-about",
    title: "Ports we tell nobody about",
    dek: "Little harbors, steep stairs, coffee in the square. How to find them when the big ships aren't watching.",
    category: "Cruises",
    read: "7 min read",
    date: "December 2025",
    image: "/images/blog/ports-we-tell-nobody-about.jpg",
    author: "Isaac",
  },
  {
    slug: "night-sailing-the-romance-is-real",
    title: "Night sailing: the romance is real",
    dek: "Stars above, engines below, the world asleep. Why solo travelers and couples return for the open water.",
    category: "Cruises",
    read: "6 min read",
    date: "December 2025",
    image: "/images/blog/night-sailing-the-romance-is-real.jpg",
    author: "Isaac",
  },
  {
    slug: "the-captain-knows",
    title: "The captain knows",
    dek: "Command at sea tells a different story. An essay on experience, decision, and why seasickness matters less than you think.",
    category: "Cruises",
    read: "5 min read",
    date: "November 2025",
    image: "/images/blog/the-captain-knows.jpg",
    author: "Isaac",
  },
  {
    slug: "norwegian-fjords-in-the-midnight-sun",
    title: "Norwegian fjords in the midnight sun",
    dek: "Summer in the north. Glaciers, waterfalls, and light that never quite leaves. Why it's worth the cost.",
    category: "Cruises",
    read: "8 min read",
    date: "November 2025",
    image: "/images/blog/norwegian-fjords-in-the-midnight-sun.jpg",
    author: "Isaac",
  },
  {
    slug: "canal-cruising-art-and-engineering",
    title: "Canal cruising: art and engineering",
    dek: "Panama, Corinth, Kiel—the locks are the star. How waterways reshape what travel means.",
    category: "Cruises",
    read: "7 min read",
    date: "October 2025",
    image: "/images/blog/canal-cruising-art-and-engineering.jpg",
    author: "Isaac",
  },
  {
    slug: "adventure-cruising-with-purpose",
    title: "Adventure cruising with purpose",
    dek: "Ice, wildlife, and scientists. Voyages to places that reshape how you see the world—and yourself.",
    category: "Cruises",
    read: "10 min read",
    date: "October 2025",
    image: "/images/blog/adventure-cruising-with-purpose.jpg",
    author: "Isaac",
  },
  {
    slug: "the-dining-room-at-eight",
    title: "The dining room at eight",
    dek: "Formal nights. White tablecloths. Why traditions float differently on water, and why they matter.",
    category: "Cruises",
    read: "6 min read",
    date: "September 2025",
    image: "/images/blog/the-dining-room-at-eight.jpg",
    author: "Isaac",
  },
  {
    slug: "champagne-and-sunsets-the-ritual",
    title: "Champagne and sunsets: the ritual",
    dek: "Every evening on a ship is a small ceremony. The best part of cruise travel isn't the destination—it's the hours between.",
    category: "Cruises",
    read: "5 min read",
    date: "September 2025",
    image: "/images/blog/champagne-and-sunsets-the-ritual.jpg",
    author: "Isaac",
  },
  {
    slug: "deck-chairs-and-philosophy",
    title: "Deck chairs and philosophy",
    dek: "What happens when you do nothing for seven days. Why cruise travelers return changed.",
    category: "Cruises",
    read: "7 min read",
    date: "August 2025",
    image: "/images/blog/deck-chairs-and-philosophy.jpg",
    author: "Isaac",
  },
  {
    slug: "crew-conversations-the-human-element",
    title: "Crew conversations: the human element",
    dek: "Invisible labor, visible kindness. Stories from the people who keep ships floating, hearts steady.",
    category: "Cruises",
    read: "6 min read",
    date: "August 2025",
    image: "/images/blog/crew-conversations-the-human-element.jpg",
    author: "Isaac",
  },
  {
    slug: "library-at-sea-when-books-float",
    title: "Library at sea: when books float",
    dek: "Why ship libraries matter. Time, solitude, and the pleasure of finishing what you started.",
    category: "Cruises",
    read: "5 min read",
    date: "July 2025",
    image: "/images/blog/library-at-sea-when-books-float.jpg",
    author: "Isaac",
  },
  {
    slug: "itinerary-discipline-the-unbooked-day",
    title: "Itinerary discipline: the unbooked day",
    dek: "How to cruise without cruising—staying aboard, sleeping in, remembering silence.",
    category: "Cruises",
    read: "6 min read",
    date: "July 2025",
    image: "/images/blog/itinerary-discipline-the-unbooked-day.jpg",
    author: "Isaac",
  },
  {
    slug: "secret-spots-hidden-on-big-ships",
    title: "Secret spots hidden on big ships",
    dek: "Even in 6,000-person crowds, there are corners where you're alone. How to find them.",
    category: "Cruises",
    read: "5 min read",
    date: "June 2025",
    image: "/images/blog/secret-spots-hidden-on-big-ships.jpg",
    author: "Isaac",
  },
  {
    slug: "spring-cruising-the-season-nobody-books",
    title: "Spring cruising: the season nobody books",
    dek: "March, April. The weather's fine, the prices haven't peaked, and you'll have decks to yourself.",
    category: "Cruises",
    read: "6 min read",
    date: "June 2025",
    image: "/images/blog/spring-cruising-the-season-nobody-books.jpg",
    author: "Isaac",
  },
  {
    slug: "the-first-morning-at-sea",
    title: "The first morning at sea",
    dek: "When land disappears and the ocean becomes your only horizon. What that silence teaches you.",
    category: "Cruises",
    read: "5 min read",
    date: "May 2025",
    image: "/images/blog/the-first-morning-at-sea.jpg",
    author: "Isaac",
  },
  {
    slug: "wine-and-water-tasting-the-voyage",
    title: "Wine and water: tasting the voyage",
    dek: "A sommelier at sea knows something about seasons, terroir, and what water tastes like when the ship moves.",
    category: "Cruises",
    read: "7 min read",
    date: "May 2025",
    image: "/images/blog/wine-and-water-tasting-the-voyage.jpg",
    author: "Isaac",
  },
  {
    slug: "star-gazing-from-a-moving-ship",
    title: "Star-gazing from a moving ship",
    dek: "Away from light pollution, away from land. Why astronomers sail, and why you should too.",
    category: "Cruises",
    read: "6 min read",
    date: "April 2025",
    image: "/images/blog/star-gazing-from-a-moving-ship.jpg",
    author: "Isaac",
  },
  {
    slug: "crossing-the-date-line-time-travel",
    title: "Crossing the date line: time travel",
    dek: "You leave Tuesday and arrive on Tuesday. The calendar breaks, and something opens in you.",
    category: "Cruises",
    read: "6 min read",
    date: "April 2025",
    image: "/images/blog/crossing-the-date-line-time-travel.jpg",
    author: "Isaac",
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getRelated(slug: string, n = 3): Post[] {
  const me = getPost(slug);
  if (!me) return posts.slice(0, n);
  return posts.filter((p) => p.slug !== slug && p.category === me.category).slice(0, n).concat(
    posts.filter((p) => p.slug !== slug && p.category !== me.category).slice(0, Math.max(0, n))
  ).slice(0, n);
}
