import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Top ~250 international airports: [IATA, City, Country]
const AIRPORTS: [string, string, string][] = [
  ["JFK","New York (JFK)","US"],["LGA","New York (LaGuardia)","US"],["EWR","Newark","US"],
  ["LAX","Los Angeles","US"],["ORD","Chicago O'Hare","US"],["MDW","Chicago Midway","US"],
  ["MIA","Miami","US"],["FLL","Fort Lauderdale","US"],["MCO","Orlando","US"],
  ["TPA","Tampa","US"],["ATL","Atlanta","US"],["DFW","Dallas/Fort Worth","US"],
  ["IAH","Houston Bush","US"],["HOU","Houston Hobby","US"],["DEN","Denver","US"],
  ["PHX","Phoenix","US"],["LAS","Las Vegas","US"],["SEA","Seattle","US"],
  ["SFO","San Francisco","US"],["OAK","Oakland","US"],["SJC","San Jose","US"],
  ["BOS","Boston","US"],["DCA","Washington DC (Reagan)","US"],["IAD","Washington DC (Dulles)","US"],
  ["BWI","Baltimore","US"],["PHL","Philadelphia","US"],["CLT","Charlotte","US"],
  ["MSP","Minneapolis","US"],["DTW","Detroit","US"],["MSY","New Orleans","US"],
  ["SLC","Salt Lake City","US"],["PDX","Portland","US"],["SAN","San Diego","US"],
  ["MCI","Kansas City","US"],["CMH","Columbus","US"],["CLE","Cleveland","US"],
  ["PIT","Pittsburgh","US"],["RDU","Raleigh-Durham","US"],["STL","St. Louis","US"],
  ["AUS","Austin","US"],["SAT","San Antonio","US"],["DAL","Dallas Love Field","US"],
  ["HNL","Honolulu","US"],["ANC","Anchorage","US"],["SNA","Orange County","US"],
  ["BUR","Burbank","US"],["LGB","Long Beach","US"],["SMF","Sacramento","US"],
  ["LHR","London Heathrow","GB"],["LGW","London Gatwick","GB"],["STN","London Stansted","GB"],
  ["LCY","London City","GB"],["MAN","Manchester","GB"],["BHX","Birmingham","GB"],
  ["EDI","Edinburgh","GB"],["GLA","Glasgow","GB"],["BRS","Bristol","GB"],
  ["CDG","Paris Charles de Gaulle","FR"],["ORY","Paris Orly","FR"],["NCE","Nice","FR"],
  ["MRS","Marseille","FR"],["LYS","Lyon","FR"],["TLS","Toulouse","FR"],["BOD","Bordeaux","FR"],
  ["FRA","Frankfurt","DE"],["MUC","Munich","DE"],["BER","Berlin","DE"],
  ["HAM","Hamburg","DE"],["DUS","Düsseldorf","DE"],["CGN","Cologne","DE"],["STR","Stuttgart","DE"],
  ["AMS","Amsterdam","NL"],["EIN","Eindhoven","NL"],
  ["ZRH","Zurich","CH"],["GVA","Geneva","CH"],["BSL","Basel","CH"],
  ["VIE","Vienna","AT"],["SZG","Salzburg","AT"],["INN","Innsbruck","AT"],
  ["BCN","Barcelona","ES"],["MAD","Madrid","ES"],["AGP","Málaga","ES"],
  ["PMI","Palma de Mallorca","ES"],["IBZ","Ibiza","ES"],["VLC","Valencia","ES"],
  ["SVQ","Seville","ES"],["LPA","Gran Canaria","ES"],["TFN","Tenerife North","ES"],
  ["FCO","Rome Fiumicino","IT"],["CIA","Rome Ciampino","IT"],["MXP","Milan Malpensa","IT"],
  ["LIN","Milan Linate","IT"],["BGY","Milan Bergamo","IT"],["VCE","Venice","IT"],
  ["FLR","Florence","IT"],["NAP","Naples","IT"],["BRI","Bari","IT"],["PMO","Palermo","IT"],
  ["CPH","Copenhagen","DK"],["ARN","Stockholm Arlanda","SE"],["GOT","Gothenburg","SE"],
  ["OSL","Oslo","NO"],["BGO","Bergen","NO"],["HEL","Helsinki","FI"],
  ["LIS","Lisbon","PT"],["OPO","Porto","PT"],["FAO","Faro","PT"],
  ["ATH","Athens","GR"],["HER","Heraklion","GR"],["RHO","Rhodes","GR"],["SKG","Thessaloniki","GR"],
  ["DUB","Dublin","IE"],["SNN","Shannon","IE"],["BRU","Brussels","BE"],
  ["WAW","Warsaw","PL"],["KRK","Krakow","PL"],["BUD","Budapest","HU"],
  ["PRG","Prague","CZ"],["BTS","Bratislava","SK"],["ZAG","Zagreb","HR"],
  ["DBV","Dubrovnik","HR"],["SPU","Split","HR"],["LJU","Ljubljana","SI"],
  ["BEG","Belgrade","RS"],["SOF","Sofia","BG"],["OTP","Bucharest","RO"],
  ["RIX","Riga","LV"],["TLL","Tallinn","EE"],["VNO","Vilnius","LT"],
  ["IST","Istanbul","TR"],["SAW","Istanbul Sabiha Gökçen","TR"],["AYT","Antalya","TR"],["ADB","Izmir","TR"],
  ["DXB","Dubai","AE"],["AUH","Abu Dhabi","AE"],["SHJ","Sharjah","AE"],
  ["DOH","Doha","QA"],["KWI","Kuwait City","KW"],["BAH","Bahrain","BH"],["MCT","Muscat","OM"],
  ["TLV","Tel Aviv","IL"],["AMM","Amman","JO"],["BEY","Beirut","LB"],
  ["CAI","Cairo","EG"],["HRG","Hurghada","EG"],["SSH","Sharm el-Sheikh","EG"],
  ["CMN","Casablanca","MA"],["RAK","Marrakech","MA"],["AGA","Agadir","MA"],
  ["TUN","Tunis","TN"],["ALG","Algiers","DZ"],["TIP","Tripoli","LY"],
  ["ADD","Addis Ababa","ET"],["NBO","Nairobi","KE"],["MBA","Mombasa","KE"],
  ["DAR","Dar es Salaam","TZ"],["JRO","Kilimanjaro","TZ"],["EBB","Entebbe","UG"],
  ["ACC","Accra","GH"],["LOS","Lagos","NG"],["ABV","Abuja","NG"],["JNB","Johannesburg","ZA"],
  ["CPT","Cape Town","ZA"],["DUR","Durban","ZA"],["HRE","Harare","ZW"],
  ["LUN","Lusaka","ZM"],["WDH","Windhoek","NA"],["GBE","Gaborone","BW"],
  ["NAS","Nassau","BS"],["MBJ","Montego Bay","JM"],["KIN","Kingston","JM"],
  ["PUJ","Punta Cana","DO"],["SDQ","Santo Domingo","DO"],["SJU","San Juan","PR"],
  ["BGI","Bridgetown","BB"],["GEO","Georgetown","GY"],["PBM","Paramaribo","SR"],
  ["GRU","São Paulo Guarulhos","BR"],["GIG","Rio de Janeiro Galeão","BR"],
  ["CNF","Belo Horizonte","BR"],["BSB","Brasília","BR"],["FOR","Fortaleza","BR"],
  ["REC","Recife","BR"],["POA","Porto Alegre","BR"],["CWB","Curitiba","BR"],
  ["EZE","Buenos Aires Ezeiza","AR"],["AEP","Buenos Aires Aeroparque","AR"],
  ["SCL","Santiago","CL"],["LIM","Lima","PE"],["BOG","Bogotá","CO"],
  ["MDE","Medellín","CO"],["CTG","Cartagena","CO"],["UIO","Quito","EC"],
  ["GYE","Guayaquil","EC"],["VVI","Santa Cruz","BO"],["ASU","Asunción","PY"],
  ["MVD","Montevideo","UY"],["CCS","Caracas","VE"],["GUA","Guatemala City","GT"],
  ["SAP","San Pedro Sula","HN"],["MGA","Managua","NI"],["SJO","San José","CR"],
  ["PTY","Panama City","PA"],["MEX","Mexico City","MX"],["GDL","Guadalajara","MX"],
  ["MTY","Monterrey","MX"],["CUN","Cancún","MX"],["SJD","Los Cabos","MX"],
  ["PVR","Puerto Vallarta","MX"],["HMO","Hermosillo","MX"],["TIJ","Tijuana","MX"],
  ["YYZ","Toronto Pearson","CA"],["YYC","Calgary","CA"],["YVR","Vancouver","CA"],
  ["YUL","Montréal","CA"],["YOW","Ottawa","CA"],["YEG","Edmonton","CA"],
  ["YHZ","Halifax","CA"],["YWG","Winnipeg","CA"],
  ["NRT","Tokyo Narita","JP"],["HND","Tokyo Haneda","JP"],["KIX","Osaka Kansai","JP"],
  ["ITM","Osaka Itami","JP"],["CTS","Sapporo","JP"],["FUK","Fukuoka","JP"],["OKA","Okinawa","JP"],
  ["ICN","Seoul Incheon","KR"],["GMP","Seoul Gimpo","KR"],["PUS","Busan","KR"],
  ["PEK","Beijing Capital","CN"],["PKX","Beijing Daxing","CN"],["PVG","Shanghai Pudong","CN"],
  ["SHA","Shanghai Hongqiao","CN"],["CAN","Guangzhou","CN"],["SZX","Shenzhen","CN"],
  ["CTU","Chengdu","CN"],["KMG","Kunming","CN"],["XIY","Xi'an","CN"],
  ["HKG","Hong Kong","HK"],["MFM","Macau","MO"],["TPE","Taipei Taoyuan","TW"],["TSA","Taipei Songshan","TW"],
  ["SIN","Singapore","SG"],["KUL","Kuala Lumpur","MY"],["BKI","Kota Kinabalu","MY"],
  ["CGK","Jakarta","ID"],["DPS","Bali Denpasar","ID"],["SUB","Surabaya","ID"],
  ["MNL","Manila","PH"],["CEB","Cebu","PH"],["BKK","Bangkok Suvarnabhumi","TH"],
  ["DMK","Bangkok Don Mueang","TH"],["HKT","Phuket","TH"],["CNX","Chiang Mai","TH"],
  ["SGN","Ho Chi Minh City","VN"],["HAN","Hanoi","VN"],["DAD","Da Nang","VN"],
  ["RGN","Yangon","MM"],["PNH","Phnom Penh","KH"],["REP","Siem Reap","KH"],
  ["VTE","Vientiane","LA"],["CMB","Colombo","LK"],["DAC","Dhaka","BD"],
  ["KTM","Kathmandu","NP"],["BOM","Mumbai","IN"],["DEL","Delhi","IN"],
  ["BLR","Bangalore","IN"],["MAA","Chennai","IN"],["CCU","Kolkata","IN"],
  ["HYD","Hyderabad","IN"],["COK","Kochi","IN"],["AMD","Ahmedabad","IN"],
  ["GOI","Goa","IN"],["PNQ","Pune","IN"],["KHI","Karachi","PK"],["LHE","Lahore","PK"],
  ["ISB","Islamabad","PK"],["KBL","Kabul","AF"],["TAS","Tashkent","UZ"],
  ["ALA","Almaty","KZ"],["TBS","Tbilisi","GE"],["EVN","Yerevan","AM"],["GYD","Baku","AZ"],
  ["LED","St. Petersburg","RU"],["SVO","Moscow Sheremetyevo","RU"],["DME","Moscow Domodedovo","RU"],
  ["OTP","Bucharest Otopeni","RO"],
  ["SYD","Sydney","AU"],["MEL","Melbourne","AU"],["BNE","Brisbane","AU"],
  ["PER","Perth","AU"],["ADL","Adelaide","AU"],["CBR","Canberra","AU"],
  ["AKL","Auckland","NZ"],["CHC","Christchurch","NZ"],["WLG","Wellington","NZ"],
  ["PPT","Tahiti Faa'a","PF"],["NAN","Nadi Fiji","FJ"],["APW","Apia","WS"],
  ["HIR","Honiara","SB"],["VLI","Port Vila","VU"],
];

export async function GET(req: NextRequest) {
  const q = (req.nextUrl.searchParams.get("q") ?? "").trim().toUpperCase();
  if (q.length < 1) return NextResponse.json({ airports: [] });

  const results = AIRPORTS.filter(([code, city]) =>
    code.startsWith(q) || city.toUpperCase().includes(q)
  ).slice(0, 8);

  return NextResponse.json({
    airports: results.map(([code, city, country]) => ({ code, label: `${code} — ${city}`, city, country })),
  });
}
